# Generated by Django 5.0.1 on 2024-01-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_rename_user_full_name_user_model_users_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_full_name', models.CharField(max_length=100)),
                ('order_phone_number', models.CharField(max_length=100)),
                ('order_email', models.EmailField(max_length=100)),
                ('order_address', models.CharField(max_length=200)),
                ('order_address2', models.CharField(max_length=200)),
                ('order_location', models.CharField(max_length=200)),
                ('order_quantity', models.CharField(max_length=100)),
            ],
        ),
    ]
