# Generated by Django 5.0.1 on 2024-01-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_contact_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_model',
            name='order_remark',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
