# Generated by Django 5.0 on 2024-01-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_panel',
            name='admin_email',
            field=models.EmailField(max_length=100),
        ),
    ]
