# Generated by Django 5.0 on 2024-01-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_add_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_panel',
            name='image',
            field=models.ImageField(default='p.jpg', upload_to='media/prof_pic'),
        ),
    ]
